# Generated by Django 3.1.2 on 2020-10-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyDjangoApi_App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
